ConeDetection : ConeDetection.h ConeDetection_edge.cpp ConeDetection_right.cpp ConeDetection_apex.cpp ConeDetection_detect.cpp ConeDetection.cpp ConeDetection_execute.cpp ConeDetectionMAIN.cpp
	g++ `pkg-config --cflags opencv` ConeDetection.h ConeDetection_edge.cpp ConeDetection_right.cpp ConeDetection_apex.cpp ConeDetection_detect.cpp ConeDetection.cpp ConeDetection_execute.cpp ConeDetectionMAIN.cpp -L/usr/local/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_calib3d -o ConeDetection


